from Header import CppHeader

class BinaryIntrospection(object):
    warning = '//Warning! This file is generated by BinaryIntrospection. Edit at your own risk.\n'
    
    prefix = 'char introspection_xml[] = {'

    suffix = ' 0x00\n};'

    def __init__(self, dbus):
        self.dbus = dbus

    def write(self, filename):
        fd = open(filename, 'w')
        fd.write(self.warning)
        fd.write(CppHeader)
        fd.write(self.prefix)
        fd.write(self.convert())
        fd.write(self.suffix)
        fd.close()

    def convert(self):
        cnt = 0
        value = ''
        for char in self.dbus.xml():
            if cnt % 12 == 0:
                value += '\n  '
            else:
                value += ' '
            value += '0x%02x,' % ord(char)
            cnt += 1
        return value
